USE [DESAFIO]
GO

/****** Object:  Table [dbo].[Languages]    Script Date: 18/01/2021 05:51:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Languages](
	[ISOCodeC] [char](2) NOT NULL,
	[ISOCode] [char](3) NOT NULL,
	[Name] [nchar](30) NOT NULL,
 CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED 
(
	[ISOCodeC] ASC,
	[ISOCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

