USE [master]
GO

/****** Object:  Database [DESAFIO]    Script Date: 18/01/2021 05:49:41 ******/
CREATE DATABASE [DESAFIO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DESAFIO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DESAFIO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DESAFIO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DESAFIO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DESAFIO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DESAFIO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DESAFIO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DESAFIO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DESAFIO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DESAFIO] SET ARITHABORT OFF 
GO

ALTER DATABASE [DESAFIO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DESAFIO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DESAFIO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DESAFIO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DESAFIO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DESAFIO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DESAFIO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DESAFIO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DESAFIO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DESAFIO] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DESAFIO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DESAFIO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DESAFIO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DESAFIO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DESAFIO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DESAFIO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DESAFIO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DESAFIO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DESAFIO] SET  MULTI_USER 
GO

ALTER DATABASE [DESAFIO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DESAFIO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DESAFIO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DESAFIO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DESAFIO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DESAFIO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DESAFIO] SET  READ_WRITE 
GO


